version: '3.8'
services:
  notfallakte-app:
    build: .
    container_name: notfallakte
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rote-mappe.entrypoints=https"
      - "traefik.http.routers.rote-mappe.rule=Host(`notfall.lokal.weigl.family`)"
      - "traefik.http.routers.rote-mappe.tls=true"
      - "traefik.http.routers.rote-mappe.tls.certresolver=ionos"
      - "traefik.http.routers.rote-mappe.middlewares=default-headers@file"
      - "traefik.http.services.rote-mappe.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: '0.25'
        reservations:
          memory: 32m
 
networks:
  proxy:
    external: true
